# Generated by Django 4.0.3 on 2022-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Cpesticides'), ('F', 'Fertlizers'), ('PE', 'Pesticides'), ('E', 'Equipment')], max_length=2),
        ),
    ]
