# Generated by Django 4.0.3 on 2022-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_id_alter_customer_id_alter_orderplaced_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Rajasthan', 'Rajasthan'), ('Karnataka', 'Karnataka'), ('Gujarat', 'Gujarat'), ('Orissa', 'Orissa'), ('Kerala', 'Kerala'), ('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Punjab', 'Punjab'), ('Chhattisgarh', 'Chhattisgarh'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Uttarakhand', 'Uttarakhand'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Tripura', 'Tripura'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Nagaland', 'Nagaland'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Puducherry', 'Puducherry'), ('Mizoram', 'Mizoram'), ('Chandigarh', 'Chandigarh'), ('Sikkim', 'Sikkim'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Telangana', 'Telangana')], default='Telangana', max_length=50),
        ),
    ]
